remote_theme: b2a3e8/jekyll-theme-console
title: Sales Advocate Solution
description: The next generation in procurement support.


header_pages:
  - index.md
  - about.md
  - pricing.md

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true

# footer: 'follow us on <a href="https://twitter.com/xxx">twitter</a>'

# google_analytics: UA-NNNNNNNN-N
