remote_theme: "jeffreytse/jekyll-theme-yat"
title: Sales Advocate Solution
description: The next generation in procurement support.
markdown: GFM

header_pages:
  - index.md
  - about.md
  - pricing.md

plugins:
  - jekyll-remote-theme
# footer: 'follow us on <a href="https://twitter.com/xxx">twitter</a>'

# google_analytics: UA-NNNNNNNN-N
